image layers added

diff --git a/build/android-28/Dockerfile b/build/android-28/Dockerfile
--- a/build/android-28/Dockerfile
+++ b/build/android-28/Dockerfile
@@ -34,13 +34,20 @@ RUN dpkg --add-architecture i386 && \
 
     # Customized steps per specific platform
     yes | sdkmanager --no_https --licenses --sdk_root=/opt/android-sdk-linux && \
-    yes | sdkmanager --sdk_root=/opt/android-sdk-linux emulator tools platform-tools "platforms;android-28" "system-images;android-28;google_apis;x86_64" --verbose | uniq && \
+
+    # Clean up
+    apt-get -yq autoremove && \
+    apt-get clean && \
+    apt-get autoclean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+RUN yes | sdkmanager --sdk_root=/opt/android-sdk-linux emulator tools platform-tools "platforms;android-28" "system-images;android-28;google_apis;x86_64" --verbose | uniq && \
 
     echo no | avdmanager create avd -n "x86" --package "system-images;android-28;google_apis;x86_64" --tag google_apis && \
 
     # Unfilter devices (now local because CI downloads from github are unstable)
     # curl -o /root/.android/adb_usb.ini https://raw.githubusercontent.com/apkudo/adbusbini/master/adb_usb.ini && \
-    DEBIAN_FRONTEND=noninteractive apt-get purge -yq unzip openjdk-8-jdk && \
+#    DEBIAN_FRONTEND=noninteractive apt-get purge -yq unzip openjdk-8-jdk && \
 
     # fix kernel
 #    if [ -f /opt/android-sdk-linux/system-images/android-28/google_apis/x86/kernel-ranchu-64 ]; then cp /opt/android-sdk-linux/system-images/android-28/google_apis/x86/kernel-ranchu-64  /opt/android-sdk-linux/system-images/android-28/google_apis/x86/kernel-ranchu; fi && \
@@ -53,13 +60,7 @@ RUN dpkg --add-architecture i386 && \
     qemu-img convert -O qcow2 -c /root/.android/avd/x86.avd/userdata.img /root/.android/avd/x86.avd/userdata.qcow2 && \
     mv /root/.android/avd/x86.avd/userdata.qcow2 /root/.android/avd/x86.avd/userdata.img && \
     (qemu-img convert -O qcow2 -c /opt/android-sdk-linux/system-images/android-28/google_apis/x86_64/vendor.img /opt/android-sdk-linux/system-images/android-28/google_apis/x86_64/vendor.qcow2 && \
-    mv /opt/android-sdk-linux/system-images/android-28/google_apis/x86_64/vendor.qcow2 /opt/android-sdk-linux/system-images/android-28/google_apis/x86_64/vendor.img || true) && \
-
-    # Clean up
-    apt-get -yq autoremove && \
-    apt-get clean && \
-    apt-get autoclean && \
-    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+    mv /opt/android-sdk-linux/system-images/android-28/google_apis/x86_64/vendor.qcow2 /opt/android-sdk-linux/system-images/android-28/google_apis/x86_64/vendor.img || true)
 
 COPY config.ini /root/.android/avd/x86.avd/config.ini
 
